from __future__ import annotations

from typing import Protocol

from app.modules.children.domain.models import Child
from app.modules.tasks.domain.models import ChildTask, Task, TaskData


class ChildTaskRepository(Protocol):
    async def list_child_tasks(self, child: Child) -> list[ChildTask]: ...

    async def get_library_task(self, task_id: str) -> Task | None: ...

    async def get_child_task(self, child_task_id: str) -> ChildTask | None: ...

    async def load_task_source(self, child_task: ChildTask) -> Task | TaskData | None: ...

    async def insert_child_task(self, child_task: ChildTask) -> ChildTask: ...

    async def save_child_task(self, child_task: ChildTask) -> ChildTask: ...

    async def delete_child_task(self, child_task: ChildTask) -> None: ...
